// Mocks generated by Mockito 5.4.6 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:convert' as _i33;
import 'dart:typed_data' as _i34;
import 'dart:ui' as _i27;

import 'package:core/common/failure.dart' as _i19;
import 'package:core/common/state_enum.dart' as _i25;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/src/widgets/navigator.dart' as _i32;
import 'package:flutter_bloc/flutter_bloc.dart' as _i31;
import 'package:http/http.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:search/domain/entities/media.dart' as _i30;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i22;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_model.dart' as _i23;
import 'package:tv/domain/entities/tv.dart' as _i20;
import 'package:tv/domain/entities/tv_detail.dart' as _i21;
import 'package:tv/domain/repositories/tv_repository.dart' as _i4;
import 'package:tv/domain/usecases/get_on_the_air_tvs.dart' as _i29;
import 'package:tv/domain/usecases/get_popular_tvs.dart' as _i5;
import 'package:tv/domain/usecases/get_top_rated_tvs.dart' as _i6;
import 'package:tv/domain/usecases/get_tv_detail.dart' as _i8;
import 'package:tv/domain/usecases/get_tv_recommendations.dart' as _i9;
import 'package:tv/presentation/bloc/popular_tvs/popular_tvs_bloc.dart' as _i16;
import 'package:tv/presentation/bloc/top_rated_tvs/top_rated_tvs_bloc.dart'
    as _i15;
import 'package:tv/presentation/bloc/tv_detail/tv_detail_bloc.dart' as _i13;
import 'package:tv/presentation/bloc/tv_list/tv_list_bloc.dart' as _i14;
import 'package:tv/presentation/provider/popular_tvs_notifier.dart' as _i24;
import 'package:tv/presentation/provider/top_rated_tvs_notifier.dart' as _i28;
import 'package:watchlist/domain/repositories/watchlist_repository.dart' as _i7;
import 'package:watchlist/domain/usecases/get_watchlist_status.dart' as _i10;
import 'package:watchlist/domain/usecases/remove_watchlist.dart' as _i12;
import 'package:watchlist/domain/usecases/save_watchlist.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvDetailResponse {
  _FakeTvDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvRepository_2 extends _i1.SmartFake implements _i4.TvRepository {
  _FakeTvRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTvs_3 extends _i1.SmartFake implements _i5.GetPopularTvs {
  _FakeGetPopularTvs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTvs_4 extends _i1.SmartFake
    implements _i6.GetTopRatedTvs {
  _FakeGetTopRatedTvs_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistRepository_5 extends _i1.SmartFake
    implements _i7.WatchlistRepository {
  _FakeWatchlistRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvDetail_6 extends _i1.SmartFake implements _i8.GetTvDetail {
  _FakeGetTvDetail_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvRecommendations_7 extends _i1.SmartFake
    implements _i9.GetTvRecommendations {
  _FakeGetTvRecommendations_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistStatus_8 extends _i1.SmartFake
    implements _i10.GetWatchlistStatus {
  _FakeGetWatchlistStatus_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistItem_9 extends _i1.SmartFake
    implements _i11.SaveWatchlistItem {
  _FakeSaveWatchlistItem_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistItem_10 extends _i1.SmartFake
    implements _i12.RemoveWatchlistItem {
  _FakeRemoveWatchlistItem_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailState_11 extends _i1.SmartFake
    implements _i13.TvDetailState {
  _FakeTvDetailState_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvListState_12 extends _i1.SmartFake implements _i14.TvListState {
  _FakeTvListState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvsState_13 extends _i1.SmartFake
    implements _i15.TopRatedTvsState {
  _FakeTopRatedTvsState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvsState_14 extends _i1.SmartFake
    implements _i16.PopularTvsState {
  _FakePopularTvsState_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_15 extends _i1.SmartFake implements _i17.Response {
  _FakeResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_16 extends _i1.SmartFake
    implements _i17.StreamedResponse {
  _FakeStreamedResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i4.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> getOnTheAirTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvs, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#getOnTheAirTvs, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvs, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#getPopularTvs, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvs, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#getTopRatedTvs, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>>.value(
                  _FakeEither_0<_i19.Failure, _i21.TvDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> getTvRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#getTvRecommendations, [id]),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> searchTvs(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvs, [query]),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#searchTvs, [query]),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i22.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<List<_i23.TvModel>> getOnTheAirTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvs, []),
            returnValue: _i18.Future<List<_i23.TvModel>>.value(
              <_i23.TvModel>[],
            ),
          )
          as _i18.Future<List<_i23.TvModel>>);

  @override
  _i18.Future<List<_i23.TvModel>> getPopularTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvs, []),
            returnValue: _i18.Future<List<_i23.TvModel>>.value(
              <_i23.TvModel>[],
            ),
          )
          as _i18.Future<List<_i23.TvModel>>);

  @override
  _i18.Future<List<_i23.TvModel>> getTopRatedTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvs, []),
            returnValue: _i18.Future<List<_i23.TvModel>>.value(
              <_i23.TvModel>[],
            ),
          )
          as _i18.Future<List<_i23.TvModel>>);

  @override
  _i18.Future<_i3.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i18.Future<_i3.TvDetailResponse>.value(
              _FakeTvDetailResponse_1(
                this,
                Invocation.method(#getTvDetail, [id]),
              ),
            ),
          )
          as _i18.Future<_i3.TvDetailResponse>);

  @override
  _i18.Future<List<_i23.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i18.Future<List<_i23.TvModel>>.value(
              <_i23.TvModel>[],
            ),
          )
          as _i18.Future<List<_i23.TvModel>>);

  @override
  _i18.Future<List<_i23.TvModel>> searchTvs(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvs, [query]),
            returnValue: _i18.Future<List<_i23.TvModel>>.value(
              <_i23.TvModel>[],
            ),
          )
          as _i18.Future<List<_i23.TvModel>>);
}

/// A class which mocks [GetPopularTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvs extends _i1.Mock implements _i5.GetPopularTvs {
  MockGetPopularTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TvRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);
}

/// A class which mocks [PopularTvsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvsNotifier extends _i1.Mock
    implements _i24.PopularTvsNotifier {
  MockPopularTvsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GetPopularTvs get getPopularTvs =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTvs),
            returnValue: _FakeGetPopularTvs_3(
              this,
              Invocation.getter(#getPopularTvs),
            ),
          )
          as _i5.GetPopularTvs);

  @override
  _i25.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i25.RequestState.empty,
          )
          as _i25.RequestState);

  @override
  List<_i20.Tv> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i20.Tv>[])
          as List<_i20.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i18.Future<void> fetchPopularTvs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularTvs, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void addListener(_i27.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i27.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvsNotifier extends _i1.Mock
    implements _i28.TopRatedTvsNotifier {
  MockTopRatedTvsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetTopRatedTvs get getTopRatedTvs =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTvs),
            returnValue: _FakeGetTopRatedTvs_4(
              this,
              Invocation.getter(#getTopRatedTvs),
            ),
          )
          as _i6.GetTopRatedTvs);

  @override
  _i25.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i25.RequestState.empty,
          )
          as _i25.RequestState);

  @override
  List<_i20.Tv> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i20.Tv>[])
          as List<_i20.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i18.Future<void> fetchTopRatedTvs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedTvs, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void addListener(_i27.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i27.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetTopRatedTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvs extends _i1.Mock implements _i6.GetTopRatedTvs {
  MockGetTopRatedTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TvRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);
}

/// A class which mocks [GetOnTheAirTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvs extends _i1.Mock implements _i29.GetOnTheAirTvs {
  MockGetOnTheAirTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TvRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i8.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TvRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>>.value(
                  _FakeEither_0<_i19.Failure, _i21.TvDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, _i21.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i9.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TvRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i20.Tv>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i20.Tv>>>);
}

/// A class which mocks [GetWatchlistStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistStatus extends _i1.Mock
    implements _i10.GetWatchlistStatus {
  MockGetWatchlistStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.WatchlistRepository);

  @override
  _i18.Future<bool> execute(int? id, String? mediaType) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id, mediaType]),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);
}

/// A class which mocks [SaveWatchlistItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistItem extends _i1.Mock implements _i11.SaveWatchlistItem {
  MockSaveWatchlistItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.WatchlistRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, String>> execute(_i30.Media? item) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [item]),
            returnValue: _i18.Future<_i2.Either<_i19.Failure, String>>.value(
              _FakeEither_0<_i19.Failure, String>(
                this,
                Invocation.method(#execute, [item]),
              ),
            ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistItem extends _i1.Mock
    implements _i12.RemoveWatchlistItem {
  MockRemoveWatchlistItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.WatchlistRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeWatchlistRepository_5(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.WatchlistRepository);

  @override
  _i18.Future<_i2.Either<_i19.Failure, String>> execute(
    int? id,
    String? mediaType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id, mediaType]),
            returnValue: _i18.Future<_i2.Either<_i19.Failure, String>>.value(
              _FakeEither_0<_i19.Failure, String>(
                this,
                Invocation.method(#execute, [id, mediaType]),
              ),
            ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, String>>);
}

/// A class which mocks [TvDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailBloc extends _i1.Mock implements _i13.TvDetailBloc {
  MockTvDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_6(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i8.GetTvDetail);

  @override
  _i9.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_7(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i9.GetTvRecommendations);

  @override
  _i10.GetWatchlistStatus get getWatchlistStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistStatus),
            returnValue: _FakeGetWatchlistStatus_8(
              this,
              Invocation.getter(#getWatchlistStatus),
            ),
          )
          as _i10.GetWatchlistStatus);

  @override
  _i11.SaveWatchlistItem get saveWatchlistItem =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistItem),
            returnValue: _FakeSaveWatchlistItem_9(
              this,
              Invocation.getter(#saveWatchlistItem),
            ),
          )
          as _i11.SaveWatchlistItem);

  @override
  _i12.RemoveWatchlistItem get removeWatchlistItem =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistItem),
            returnValue: _FakeRemoveWatchlistItem_10(
              this,
              Invocation.getter(#removeWatchlistItem),
            ),
          )
          as _i12.RemoveWatchlistItem);

  @override
  _i13.TvDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvDetailState_11(this, Invocation.getter(#state)),
          )
          as _i13.TvDetailState);

  @override
  _i18.Stream<_i13.TvDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i13.TvDetailState>.empty(),
          )
          as _i18.Stream<_i13.TvDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i13.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i13.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i13.TvDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i13.TvDetailEvent>(
    _i31.EventHandler<E, _i13.TvDetailState>? handler, {
    _i31.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i31.Transition<_i13.TvDetailEvent, _i13.TvDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i31.Change<_i13.TvDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListBloc extends _i1.Mock implements _i14.TvListBloc {
  MockTvListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.TvListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvListState_12(this, Invocation.getter(#state)),
          )
          as _i14.TvListState);

  @override
  _i18.Stream<_i14.TvListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i14.TvListState>.empty(),
          )
          as _i18.Stream<_i14.TvListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i14.TvListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.TvListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i14.TvListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.TvListEvent>(
    _i31.EventHandler<E, _i14.TvListState>? handler, {
    _i31.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i31.Transition<_i14.TvListEvent, _i14.TvListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i31.Change<_i14.TvListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i32.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i32.Route<dynamic>? route,
    _i32.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i32.Route<dynamic>? route, _i32.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i32.Route<dynamic>? route,
    _i32.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i32.Route<dynamic>? newRoute,
    _i32.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i32.Route<dynamic>? topRoute,
    _i32.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i32.Route<dynamic>? route,
    _i32.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvsBloc extends _i1.Mock implements _i15.TopRatedTvsBloc {
  MockTopRatedTvsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.TopRatedTvsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvsState_13(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i15.TopRatedTvsState);

  @override
  _i18.Stream<_i15.TopRatedTvsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i15.TopRatedTvsState>.empty(),
          )
          as _i18.Stream<_i15.TopRatedTvsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i15.TopRatedTvsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i15.TopRatedTvsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i15.TopRatedTvsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i15.TopRatedTvsEvent>(
    _i31.EventHandler<E, _i15.TopRatedTvsState>? handler, {
    _i31.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i31.Transition<_i15.TopRatedTvsEvent, _i15.TopRatedTvsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i31.Change<_i15.TopRatedTvsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvsBloc extends _i1.Mock implements _i16.PopularTvsBloc {
  MockPopularTvsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.PopularTvsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvsState_14(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i16.PopularTvsState);

  @override
  _i18.Stream<_i16.PopularTvsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i16.PopularTvsState>.empty(),
          )
          as _i18.Stream<_i16.PopularTvsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i16.PopularTvsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i16.PopularTvsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i16.PopularTvsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i16.PopularTvsEvent>(
    _i31.EventHandler<E, _i16.PopularTvsState>? handler, {
    _i31.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i31.Transition<_i16.PopularTvsEvent, _i16.PopularTvsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i31.Change<_i16.PopularTvsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i7.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i2.Either<_i19.Failure, String>> saveWatchlist(
    _i30.Media? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [item]),
            returnValue: _i18.Future<_i2.Either<_i19.Failure, String>>.value(
              _FakeEither_0<_i19.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [item]),
              ),
            ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, String>>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, String>> removeWatchlist(
    int? id,
    String? mediaType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [id, mediaType]),
            returnValue: _i18.Future<_i2.Either<_i19.Failure, String>>.value(
              _FakeEither_0<_i19.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [id, mediaType]),
              ),
            ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, String>>);

  @override
  _i18.Future<bool> isAddedToWatchlist(int? id, String? mediaType) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id, mediaType]),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);

  @override
  _i18.Future<_i2.Either<_i19.Failure, List<_i30.Media>>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue:
                _i18.Future<_i2.Either<_i19.Failure, List<_i30.Media>>>.value(
                  _FakeEither_0<_i19.Failure, List<_i30.Media>>(
                    this,
                    Invocation.method(#getWatchlist, []),
                  ),
                ),
          )
          as _i18.Future<_i2.Either<_i19.Failure, List<_i30.Media>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i17.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<_i17.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<_i17.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<_i17.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<_i17.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<_i17.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<_i17.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i18.Future<_i17.Response>.value(
              _FakeResponse_15(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i18.Future<_i17.Response>);

  @override
  _i18.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i18.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i18.Future<String>);

  @override
  _i18.Future<_i34.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i18.Future<_i34.Uint8List>.value(_i34.Uint8List(0)),
          )
          as _i18.Future<_i34.Uint8List>);

  @override
  _i18.Future<_i17.StreamedResponse> send(_i17.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i18.Future<_i17.StreamedResponse>.value(
              _FakeStreamedResponse_16(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i18.Future<_i17.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
