// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsyOCB4TfMxfy6LoT3o0Qrb2FWnai0Xsw',
    appId: '1:322567994314:web:8022f0555b49a9cadaad33',
    messagingSenderId: '322567994314',
    projectId: 'rizal-fire-shop',
    authDomain: 'rizal-fire-shop.firebaseapp.com',
    databaseURL: 'https://rizal-fire-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizal-fire-shop.appspot.com',
    measurementId: 'G-LMMKQ77B0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH9nzn4-2i65v9jHXRl69bjinkezgnRHw',
    appId: '1:322567994314:android:b611ee60b2542f4cdaad33',
    messagingSenderId: '322567994314',
    projectId: 'rizal-fire-shop',
    databaseURL: 'https://rizal-fire-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizal-fire-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmovKPCmj996LUrWzm1ecHcI4mnIGK4j0',
    appId: '1:322567994314:ios:6954ede289db914adaad33',
    messagingSenderId: '322567994314',
    projectId: 'rizal-fire-shop',
    databaseURL: 'https://rizal-fire-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizal-fire-shop.appspot.com',
    androidClientId: '322567994314-h42n8a4g94gp9udbrpeorehjesa5u1k7.apps.googleusercontent.com',
    iosClientId: '322567994314-7sgc0ufbb0csh4l86tmdst2vjug8m70b.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.expertapp',
  );
}
